### PR TITLE
Pygobject

### PR DESCRIPTION
**Pull request by mazes-80**
Update the menu editor to pygobject/python3
wip

### CODE REVIEW

**Comment by ShadowKyogre** [comment]
Hi @mazes-80 ! I'm thumbing through the changes that you've made and it looks like you did a lot of the same work on the gtk3 branch. Which I admittedly haven't updated it against the master, so...

Thanks bunches for doing this. I'll give it a whirl, then merge after I'm done testing the changes here.

**Comment by ShadowKyogre** [comment]
All right, everything works. I'll merge this.

**Comment by ShadowKyogre** [comment]
Also forgot to mention in previous comment that I'm sure you also caught stuff that I missed during my initial port. Somehow forgot to write that in before hitting submit.

**Comment by mazes-80** [comment]
Drag'n'drop is broken.
I'll try to fix it.

**Pull request merged**
